### ISSUE TITLE
Is the Real trait is too broad? (or too specialized)

### ISSUE THREAD

**Issue by mathintro** [rustsim/alga#57]
I think it would be beneficial to have traits for functions (exp, sin, pow, ...) that are separate from numbers (partialOrd, Signed, ...). For example, when one wants to use complex numbers (since ComplexNumbers are now implementing a lot of the alga traits now) it is not uniquely defined how to order them. Nevertheless it would be great to be able to have the exp, log, ... functions in a trait without requiring them to be ordered in any way. It would be an equivalent of the Num, NumOps trait of the num_trait crate.

What do you think?

**Comment by mathintro** [comment]
Actually I would even not have a specific number name. They could be arranged in whatever traits: transcendental, algebraic, ... (I am very bad at making this kind of naming and regrouping :-)). The vast majority of these functions which are applied to tuples of real numbers basically can implement all these functions (dual numbers or quaternions for example) so I would not have a naming for a specific kind of number.

**Comment by mathintro** [comment]
I completely agree. I was more thinking about not having explicitly a ComplexTrait because the name would be misleading. These operations can be applied on very different kind of numbers.
I don't know what the @sebcrozet and @jswrenn might think about these things.

**Comment by sebcrozet** [comment]
Hey! Sorry for the late answer. I've not read this issue in-depth yet but I just wanted to tell that we agree this is an issue and that this is necessary for improving support of complex number in nalgebra.
Better complex number support is one of our goals for 2019!

I will start studying the subject more closely next month.

**Comment by sebcrozet** [comment]
Hey! Just so you know, I've started working on better Complex support. Hopefully I'll have a PR open within the next few weeks.

**Comment by Coder-256** [comment]
@sebcrozet Just curious, how do you plan to reconcile `Real` with complex numbers? There is lots of overlap. I am also working on my own version of this (as a separate fork) and the only way I found was to completely change the `Real` trait beyond any hope of backwards compatibility, which is why I'm using my own fork.

**Comment by sebcrozet** [comment]
@Coder-256 Yes, this will be breaking change. I'm basically splitting the `Real` trait in two. I'd be interested in taking a look at your fork by the way! I'll probably push (but not release) something this week-end.

**Comment by Coder-256** [comment]
@sebcrozet You've got me interested now, I'm very curious to see what you're planning. Anyway [here is my branch](https://github.com/Coder-256/magic-numbers/tree/complex) for now (in my own, separate project). I decided to fork into my own project because I plan to steer development away from just `num-traits` and make a comprehensive algebraic library like `alga` but with better support for complex numbers. However now that `num-traits` is being updated, I wonder if I might just be able to pull it in as a dependency rather than developing a similar project separately.
